# Generated by Django 5.1.7 on 2025-03-30 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the academic term (e.g., Fall 2025)', max_length=100)),
                ('term_type', models.CharField(choices=[('SEMESTER', 'Semester'), ('TRIMESTER', 'Trimester'), ('QUARTER', 'Quarter'), ('YEAR', 'Year')], default='SEMESTER', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active term')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SmartCampus Attendance System', max_length=100)),
                ('institution_name', models.CharField(default='University', max_length=200)),
                ('attendance_ip_restriction', models.BooleanField(default=True, help_text='Restrict attendance to one device per IP address')),
                ('attendance_time_window', models.IntegerField(default=15, help_text='Time window in minutes during which attendance is allowed')),
                ('allow_manual_attendance', models.BooleanField(default=True, help_text='Allow faculty to manually add attendance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
