# Generated by Django 5.1.7 on 2025-03-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_academicterm_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
