# Generated by Django 5.1.7 on 2025-03-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0005_subject_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='enrollment_key',
            field=models.CharField(blank=True, help_text='Key for students to enroll in this course', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_fname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_lname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='FacultyView.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='FacultyView.subject')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
