# Generated by Django 5.1.7 on 2025-03-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0006_subject_enrollment_key_alter_student_s_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
